version: "3.9"

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=fine_register
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - db:/var/lib/postgresql/data postgres
    ports:
      - "5441:5432"

volumes:
  db: